
version: 2.0.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Project configuration
image: Visual Studio 2013
platform: Any CPU
configuration: Release

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to

before_build:
  # Check SDKs
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  # Generates a temporary SNK. Not for real signing
  - cmd: "\"C:/Program Files/Microsoft SDKs/Windows/v7.1/Bin/sn.exe\" -k winsw_key.snk"

assembly_info:
  patch: true
  file: "**/AssemblyInfo.*"
  assembly_version:  $(appveyor_build_version)
  assembly_file_version:  $(appveyor_build_version)
  assembly_informational_version: '$(appveyor_build_version)-rc'
  
build:
  parallel: true 
  project:  src\winsw.sln 

test_script:
# Runner for NUnit2
- ps: nunit-console 'C:/projects/winsw/src/Test/winswTests/bin/Release/winswTests.dll' 'C:/projects/winsw/src/Test/winswTests/bin/Release/SharedDirectoryMapper.dll' 'C:/projects/winsw/src/Test/winswTests/bin/Release/RunawayProcessKiller.dll'

artifacts:
  - path: 'src/Core/ServiceWrapper/bin/Release/WinSW.NET2.exe'
    name: WinSW.NET2.exe
  - path: 'src/Core/ServiceWrapper_dotNET4/bin/Release/WinSW.NET4.exe'
    name: WinSW.NET4.exe



  