name: Changelog Management

on: workflow_dispatch

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
